# See https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/values.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  destination:
    name: in-cluster
    namespace: argocd
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: 8.0.17
    helm:
      valuesObject:
        server:
          extraArgs: ["--insecure"]

          service:
            type: ClusterIP

          ingress:
            enabled: true
            controller: generic
            ingressClassName: nginx
            hostname: "argocd.europe-west1-b.default.prd.novasoftworks.net"
            path: /
            pathType: Prefix
            tls: false
            annotations:
              nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
              nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
        configs:
          cm:
            application.instanceLabelKey: argocd.argoproj.io/instance
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true