# See https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/values.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  destination:
    name: in-cluster
    namespace: argocd
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: 8.0.17
    helm:
      valuesObject:
        global:
          nodeSelector:
            purpose: cluster-tools # run Argo CD on the cluster-tools node pool

          # -- Default tolerations for all components so that they can run on the cluster-tools node pool
          tolerations:
            - key: "purpose"
              operator: "Equal"
              value: "cluster-tools"
              effect: "NoSchedule"

        server:
          extraArgs: ["--insecure"]

          service:
            type: ClusterIP

          ingress:
            enabled: true
            controller: generic
            ingressClassName: nginx
            hostname: "argocd.europe-west1-b.default.prd.novasoftworks.net"
            path: /
            pathType: Prefix
            tls: true
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod
              nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
              nginx.ingress.kubernetes.io/force-ssl-redirect: "true"

        dex:
          volumes:
            - name: google-json
              secret:
                secretName: argocd-google-groups-json

          volumeMounts:
            - name: google-json
              mountPath: /tmp/oidc
              readOnly: true
              
        configs:
          cm:
            application.instanceLabelKey: argocd.argoproj.io/instance
            url: https://argocd.europe-west1-b.default.prd.novasoftworks.net
            dex.config: |
              connectors:
              - config:
                  redirectURI: https://argocd.europe-west1-b.default.prd.novasoftworks.net/api/dex/callback
                  clientID: $google-oauth:client_id
                  clientSecret: $google-oauth:client_secret
                  serviceAccountFilePath: /tmp/oidc/googleAuth.json
                  adminEmail: sso-sync@novasoftworks.com
                type: google
                id: google
                name: Google
          rbac:
            policy.csv: |
              # --- custom role ---
              p, role:writer, applications, get, *, allow
              p, role:writer, applications, create, *, allow
              p, role:writer, applications, update, *, allow
              p, role:writer, applications, sync, *, allow
              p, role:writer, logs, get, *, allow

              # --- group → role mappings ---
              g, novacp-default-admins@novasoftworks.com,  role:admin
              g, novacp-default-writers@novasoftworks.com, role:writer
              g, novacp-default-readers@novasoftworks.com, role:readonly

            policy.default: role:readonly     # anyone else can only view
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true