apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # Let’s Encrypt staging endpoint (no rate-limits)
    server: https://acme-v02.api.letsencrypt.org/directory
    email: marc.lamy@novasoftworks.com
    privateKeySecretRef:
      name: acme-letsencrypt-prod
    solvers:
      - http01:
          ingress:
            ingressClassName: nginx