apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user-identity-platform
  namespace: argocd
spec:
  project: default
  destination:
    name: in-cluster
    namespace: argocd
  source:
    repoURL: https://github.com/NovaSoftworks/cs-gitops-user-identity-platform
    targetRevision: HEAD
    path: apps/
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true