apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql
  namespace: data-stack
spec:
  instances: 1

  enableSuperuserAccess: true

  primaryUpdateStrategy: unsupervised
  
  storage:
    size: 10Gi